### ISSUE TITLE
为什么我将您的模型在外面搭出来，用其他的训练框架的代码训练，时间很久要40个小时，batchisize也只能设置成2，3来跑

### ISSUE THREAD

**Issue by yanjin12321** [lartpang/ZoomNeXt#10]
为什么我将您的模型在外面搭出来，用其他的训练框架的代码训练，时间很久要40个小时，batchisize也只能设置成2，3来跑

**Comment by lartpang** [comment]
@yanjin12321 

请问训练时开启混合精度了么？

**Comment by yanjin12321** [comment]
我在模型调用之前加了with torch.cuda.amp.autocast(enabled=True): 确实时间和batchsize都提升了  但是跑出来的mae确很高有0.09几,请问除了混合精度还有其他要注意的吗

**Comment by lartpang** [comment]
@yanjin12321 

其他的没啥，两个较小的数据集camo和chameleon上可能性能有些许波动，但是两个较大的cod10k和nc4k上性能变化不会太大。

**Comment by yanjin12321** [comment]
优化器我是直接从库里直接调的 这个和您不一样 影响大吗

**Comment by lartpang** [comment]
@yanjin12321 

我没有修改优化器本身，只是自定义了学习率调度器、可训练参数。
