### ISSUE TITLE
训练好的模型在cod10k测试集上的表现不好

### ISSUE THREAD

**Issue by JsonppOBK** [lartpang/ZoomNeXt#12]
作者您好，我使用您训练好的权重文件PvtV2B2，分别在camo,cod10k,nc4k测试集上进行测试，camo和nc4k数据集上的表现与您的结果无异，但是在cod10k上表现差别很大：sm: 0.872, wfm: 0.415, mae: 0.080, avgem: 0.895, adpem: 0.866, maxem: 0.902, avgfmeasure: 0.426, adpfmeasure: 0.413, maxfmeasure: 0.434，我应该是哪里出现问题了呢，期待您的回答。

**Comment by JsonppOBK** [comment]
我的数据集路径设置：
cod10k_tr:
  {
    root: "datasets/COD10K-v3/Train",
    image: { path: "Image", suffix: ".jpg" },
    mask: { path: "GT_Object", suffix: ".png" },
  }
camo_tr:
  {
    root: "datasets/CAMO-V.1.0-CVIU2019/Images",
    image: { path: "Train", suffix: ".jpg" },
    mask: { path: "GT", suffix: ".png" },
  }
cod10k_te:
  {
    root: "datasets/COD10K-v3/Test",
    image: { path: "Image", suffix: ".jpg" }, 
    mask: { path: "GT_Object", suffix: ".png" },
  }
camo_te:
  {
    root: "datasets/CAMO-V.1.0-CVIU2019/Images", 
    image: { path: "Test", suffix: ".jpg" },
    mask: { path: "GT", suffix: ".png" },
  }
nc4k:
  {
    root: "datasets/NC4K",
    image: { path: "Imgs", suffix: ".jpg" },
    mask: { path: "GT", suffix: ".png" },
  }

**Comment by lartpang** [comment]
@JsonppOBK 

你应该是直接使用了原始的COD10K数据集。但是实际上，在现有的方法中，大家用的都是COD10K中存在伪装目标的数据集。只占原始数据的一部分。具体可以看看SINet的设定。
