### ISSUE TITLE
cod10k数据集问题

### ISSUE THREAD

**Issue by xixioo123** [lartpang/ZoomNeXt#14]
作者您好，您实验中使用COD10K的3040张图像进行训练，我在SINet下载的cod10k数据集训练集一共有4040张图像，我想知道您是怎么筛选的？期待您的回复。

**Comment by lartpang** [comment]
@xixioo123 

这个划分方式是按照SINet的设定来的，SINet那里应该有个集成了所有训练集数据的完整数据集

**Comment by xixioo123** [comment]
> @xixioo123
> 
> 这个划分方式是按照SINet的设定来的，SINet那里应该有个集成了所有训练集数据的完整数据集

感谢您的回复   问题已解决
