### ISSUE TITLE
Dear author Dada, hello!

### ISSUE THREAD

**Issue by Genius2131** [lartpang/ZoomNeXt#2]
Dear author Dada, hello! I am a classmate of Northeast Normal University, and my research direction is the same as yours. After reading your excellent paper, I feel its excellent effect. I would like you to open the source code so that I can have the opportunity to learn from you. Thank you very much!

**Comment by lartpang** [comment]
@Genius2131 

After a long review process, our work was finally accepted by TPAMI 2024.

The code has been released after cleaning up the redundant code. Feel free to try it.
