### ISSUE TITLE
VCOD Error(s) in loading state_dict for videoPvtV2B5_ZoomNeXt

### ISSUE THREAD

**Issue by RandomStar14** [lartpang/ZoomNeXt#6]
您好，在使用您提供的指令预训练并保存预训练权重后，我尝试使用您提供的对于VCOD的微调指令：

```
python main_for_video.py --config configs/vcod_finetune.py --info finetune --model-name videoPvtV2B5_ZoomNeXt --load-from PvtV2B5_ZoomNeXt_BS4_LR0.0001_E150_H384_W384_OPMadam_OPGMfinetune_SCstep_AMP_INFOpretrain/exp_0/pth/state_final.pth
```

在执行 `io.load_weight(model=model, load_path=cfg.load_from, strict=True)`加载预训练权重时出现了以下错误：

```
RuntimeError: Error(s) in loading state_dict for videoPvtV2B5_ZoomNeXt:
        size mismatch for hmu_5.fuse.0.temperal_proj_kv.weight: copying a param with shape torch.Size([2, 1]) from checkpoint, the shape in current model is torch.Size([10, 5]).
        size mismatch for hmu_5.fuse.0.temperal_proj.0.weight: copying a param with shape torch.Size([1, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([5, 5, 3, 3]).
        size mismatch for hmu_5.fuse.0.temperal_proj.2.weight: copying a param with shape torch.Size([1, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([5, 5, 3, 3]).
        ......
```

请问是我加载权重的方式有误，还是需要在加载时改为`io.load_weight(model=model, load_path=cfg.load_from, strict=False, skip_unmatched_shape = True)` 进行非严格的权重加载（这样可以成功进行训练）

感谢您出色的工作！

**Comment by lartpang** [comment]
@RandomStar14 

是这样的，这里代码没太兼容好。因为预训练使用的实际上是单帧，但是视频时模型调整成了多帧对应的参数形状，参数上有点不兼容了。

**Comment by RandomStar14** [comment]
好的，谢谢您

**Comment by wang-ziqi993495** [comment]
> @RandomStar14
> 
> 是这样的，这里代码没改好。因为预训练使用的实际上是单帧，但是视频时模型调整成了多帧对应的参数形状，参数上有点不兼容了。
您好，我按照提问者的修改，修改代码： io.load_weight(model=model, load_path=cfg.load_from, strict=False,skip_unmatched_shape=True)后，使用单张2080ti显卡进行训练，batchsize为2，会报显存不足的错误，请问main_for_video.py的微调训练代码还能再修改完善一下吗？十分感谢

**Comment by lartpang** [comment]
@wang-ziqi993495 

您有使用混合精度么？就是config文件里的`use_amp`

如果还是显存不足的话那可能就确实占用大了一些了，可以试试使用checkpoint机制来时间换空间，这个策略我更新下。
